Python 2.4+ invalidates the timeout socket patch
The reason is that _socketobject was introduced which wraps the 'raw'
socket object.

Before this change, an URL which uses SSL would result in the following
exception which was silently ignored:

   TypeError: 'must be _socket.socket, not _socketobject'